// Axis scales. A scale owns two things: the domain it decided to show, and
// the map from a data value to an offset in the 0..size range the plot area
// gives it. Callers flip the offset for the y direction; the scale itself
// stays direction-free.

const NICE_STEPS = [1, 2, 5, 10];

// The smallest 1-2-5 step at or above `raw`, so tick spacing is always a
// number a reader can do arithmetic with.
function niceStep(raw) {
  const magnitude = 10 ** Math.floor(Math.log10(raw));
  const normalized = raw / magnitude;
  const step = NICE_STEPS.find((candidate) => candidate >= normalized) || 10;
  return step * magnitude;
}

// Ticks are generated by index rather than by repeated addition, and each one
// is rounded to the step's own precision. Both guard against 0.2 * 3 landing
// on 0.6000000000000001 and printing as a tick label.
function roundTo(value, step) {
  const decimals = Math.max(0, -Math.floor(Math.log10(step)));
  return Number(value.toFixed(Math.min(decimals, 15)));
}

/**
 * Tick values on a 1-2-5 step, extended outward to cover [min, max].
 * Requires min < max; degenerate domains are widened by the callers below.
 */
export function niceTicks(min, max, target = 5, integral = false) {
  let step = niceStep((max - min) / Math.max(1, target));
  // Counts, years and other whole-number data read badly on half steps, so
  // an integral axis never divides finer than one. A range wide enough to
  // need a coarser step already has one, and keeps it.
  if (integral && step < 1) step = 1;
  const low = Math.floor(min / step) * step;
  const count = Math.ceil((max - low) / step);
  const ticks = [];
  for (let i = 0; i <= count; i++) ticks.push(roundTo(low + i * step, step));
  return ticks;
}

// A series of identical values has no span to divide, so it gets one: 5% of
// the value, or a unit either side when the value is zero.
function widen(min, max) {
  if (min < max) return [min, max];
  const reach = Math.abs(min) * 0.05 || 1;
  return [min - reach, max + reach];
}

/**
 * A linear scale.
 * `pad` widens the data range before ticks are chosen, `zero` forces the
 * baseline into the domain, and `limits` pins the domain exactly.
 */
export function linearScale({
  min,
  max,
  size,
  pad = 0.05,
  zero = false,
  ticks: target = 5,
  limits = null,
  integral = false,
  fit = false,
}) {
  let low = zero ? Math.min(0, min) : min;
  let high = zero ? Math.max(0, max) : max;

  if (limits) {
    [low, high] = limits;
  } else if (fit) {
    // A fitted axis ends exactly where the data ends. Snapping the domain out
    // to the next round tick is what puts a phantom 2020 and 2026 either side
    // of five years of data.
    [low, high] = widen(low, high);
  } else {
    [low, high] = widen(low, high);
    const reach = (high - low) * pad;
    // An anchored baseline stays exactly on zero; padding it would put the
    // axis below the bars and lose the whole point of anchoring.
    if (!(zero && low === 0)) low -= reach;
    if (!(zero && high === 0)) high += reach;
  }

  const ticks = niceTicks(low, high, target, integral);
  const pinned = Boolean(limits) || fit;
  const domain = pinned ? [low, high] : [ticks[0], ticks.at(-1)];
  const span = domain[1] - domain[0];
  return {
    domain,
    ticks: pinned
      ? ticks.filter((tick) => tick >= domain[0] && tick <= domain[1])
      : ticks,
    map: (value) => ((value - domain[0]) / span) * size,
  };
}

/**
 * A base-10 log scale. Values at or below zero have no logarithm, so they are
 * dropped from the domain rather than turned into an error.
 */
export function logScale({ min, max, size, limits = null }) {
  let low = min;
  let high = max;
  if (limits) [low, high] = limits;
  if (high <= 0) {
    low = 1;
    high = 10;
  } else if (low <= 0) {
    // Two decades below the top is a readable default floor.
    low = 10 ** (Math.floor(Math.log10(high)) - 2);
  }

  const lowExponent = Math.floor(Math.log10(low));
  const highExponent = Math.ceil(Math.log10(high));
  const domain = [10 ** lowExponent, 10 ** highExponent];
  const span = highExponent - lowExponent;
  const ticks = [];
  for (let e = lowExponent; e <= highExponent; e++) ticks.push(10 ** e);
  return {
    domain,
    ticks,
    map: (value) =>
      value > 0 ? ((Math.log10(value) - lowExponent) / span) * size : 0,
  };
}

/**
 * A band scale for categorical x values. Points sit at band centres, so a
 * bar and a line drawn over the same categories agree on where a category is.
 */
export function categoryScale({ labels, size }) {
  const band = size / Math.max(1, labels.length);
  return {
    domain: [0, labels.length],
    band,
    labels,
    ticks: labels.map((_, index) => index),
    map: (index) => band * (index + 0.5),
  };
}

/**
 * A tick value as a reader should see it: no floating point residue, no
 * trailing zeroes, and an exponent only where the plain form would be a wall
 * of digits.
 */
export function formatTick(value) {
  if (value === 0) return "0";
  const size = Math.abs(value);
  if (size >= 1e5 || size < 1e-4)
    return value.toExponential().replace(/e\+?(-?)0*/, "e$1");
  return String(Number(value.toPrecision(12)));
}
